config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'plants#index'

  resources :plants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  enum health_status: [:dead, :wither, :bloom, :normal]

  validates :health_status, inclusion: { in: health_statuses.keys }
  validates :name, :irrigation_frequency_in_days, :health_status, presence: true

  belongs_to :species
end

app/models/species.rb
class Species < ApplicationRecord
  enum irrigation_level: [:low, :medium, :high]

  validates :irrigation_level, inclusion: { in: irrigation_levels.keys }
  validates :name, :irrigation_level, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @plants = Plant.all
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @plant = Plant.new
  end

  def index
    @plants = Plant.all
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Roślinkę dodano poprawnie.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plant/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Roślinka została zapdejtowana.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Skasowałeś roślinkę :).' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_plant
    @plant = Plant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def plant_params
    params.require(:plant).permit(:name, :species_id, :health_status, :irrigation_frequency_in_days)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waterme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to 'lista roślinek', plants_path, class: "myButton" %>

<h1>Cześć Janusz</h1>

<h2>Moje roślinki:<h2>
<ul>
  <% @plants.each do |plant| %>
    <li><%= plant.name %></li>
  <% end %>
</ul>

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "nazwa: " %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <th>Gatunek: </th>
    <%= form.collection_select(:species_id, Species.all, :id, :name) %>

  </div>

  <div class="field">
    <%= form.label "Status zdrowia: " %>
    <%= form.select(:health_status, Plant.health_statuses.keys) %>    
  </div>

  <div class="field">
    <%= form.label "Co ile dni podlewać: " %>
    <%= form.number_field :irrigation_frequency_in_days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Edytuj Roślinkę</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>lista roślinek</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>gatunek</th>
      <th>stan zdrowia</th>
      <th>Co ile dni podlewać</th>
      <th>Poziom nawodnienia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.species.name %></td>
        <td class="iconHealthStatus <%= plant.health_status %>"></td>
        <td><%= plant.irrigation_frequency_in_days %></td>
        <td><%= plant.species.irrigation_level %></td>
        <td><%= link_to 'Pokaż', plant %></td>
        <td><%= link_to 'Edytuj', edit_plant_path(plant) %></td>
        <td><%= link_to 'Skasuj', plant, method: :delete, data: { confirm: 'Jesteś pewny?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj roślinke', new_plant_path %>

<%= image_tag "health_status/normal.png" %>

app/views/plants/new.html.erb
<h1>Dodaj roślinkę</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p>
  <strong>Nazwa:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Gatunek:</strong>
  <%= @plant.species.name %>
</p>

<p>
  <strong>Ilość nawodnienia:</strong>
  <%= @plant.health_status %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/plants/waterme.html.erb
<h1>Cześć Janusz</h1>

<h2>Moje roślinki:<h2>
<ul>
  <% @plants.each do |plant| %>
    <li><%= plant.name %></li>
  <% end %>
</ul>